target = "traits/spec.md#update-trait"

# Update Trait
#
# The Update trait is used to update an item in the backing storage. The `Update::update` async function has these return values:
# 
# * In the case of a failure, the future MUST return `Err()`.
# * In the case of a success, the future MUST return `Ok(())`.
# 
# If the item already exists, it MUST be overwritten.

[[spec]]
level = "MUST"
quote = '''
* In the case of a failure, the future MUST return `Err()`.
'''

[[spec]]
level = "MUST"
quote = '''
* In the case of a success, the future MUST return `Ok(())`.
'''

[[spec]]
level = "MUST"
quote = '''
If the item already exists, it MUST be overwritten.
'''

